#!/bin/bash

# Retrieve arguments
domain=$1
path=$2

# Check domain/path availability
sudo yunohost app checkurl $domain$path -a roundcube
if [[ ! $? -eq 0 ]]; then
    exit 1
fi

# Check port availability
sudo yunohost app checkport 8786
if [[ ! $? -eq 0 ]]; then
      exit 1
  fi

# Remove trailing "/"
path=${path%/}

# Generate random cookie secret
secret=$(dd if=/dev/urandom bs=1 count=200 2> /dev/null | tr -c -d 'A-Za-z0-9' | sed -n 's/\(.\{45\}\).*/\1/p')

# Install GateOne using the setup.py
sudo mkdir -p /opt/yunohost/gateone
cd ../sources && sudo python setup.py install --record /opt/yunohost/gateone/files.txt

# Modify Nginx and GateOne configuration file, then copy them to the right place
sed -i "s@PATHTOCHANGE@$path@g" ../conf/nginx.conf
sed -i "s@PATHTOCHANGE@$path@g" ../conf/10server.conf
sed -i "s@SECRETTOCHANGE@$secret/@g" ../conf/10server.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/gateone.conf
sudo cp ../conf/10server.conf /etc/gateone/conf.d/10server.conf
sudo chmod 644 /etc/gateone/conf.d/10server.conf

# Add GateOne service to YunoHost's monitoring
sudo yunohost service add gateone --log /var/log/gateone/

# Reload GateOne, Nginx and regenerate SSOwat conf
sudo service gateone restart
sudo service nginx reload
sudo yunohost app ssowatconf
