#!/bin/bash

domain=$(sudo yunohost app setting gateone domain)
sudo service gateone stop
cat /opt/yunohost/gateone/files.txt | sudo xargs rm -rf
sudo rm -f /etc/nginx/conf.d/$domain.d/gateone.conf
sudo rm -rf /etc/gateone
sudo rm -rf /var/log/gateone
sudo rm -rf /tmp/gateone*
sudo rm -rf /var/lib/gateone

sudo yunohost service remove gateone
sudo service nginx reload
